### ISSUE TITLE
Feature: Develop Progress and Error reporting framework

### ISSUE THREAD

**Issue by danbryce** [siftech/funman#13]
To support progress and error reporting, we need a new class (e.g., `FUNMANProgress`).  The FUNMANProgress object will maintain a sequence of event lists that correspond to stages of FUNMAN processing.  Each stage will have a progress that is computed in terms of the events occurring in the stage.  The events will be either normal competition of subtasks or errors.  

The stages will include:
  - Preprocessing: Parse and instantiate input
  - Solving: Evaluating points and boxes
  - Postprocessing: Preparing outputs

This could get a little tricky because FUNMAN addresses these stages in a just-in-time fashion.  For example, evaluating a box at time 30 would involve preprocessing to develop an encoding that expresses the box at time 30, solving to determine satisfiability, and post processing to record the result.   

The progress of each stage is the proportion of the parameter space that it has completed in each stage.  The size of the parameter space is its volume, which can be infinite.  We can make it finite by automatically discarding (not labeled true nor false) boxes made up of intervals [MAX_FLOAT, inf] and [-inf, -MAX_FLOAT]. It isn't necessary to track the volume of these discarded boxes because they don't result in any measurable work.

The remaining space is within subsets of [-MAX_FLOAT, MAX_FLOAT]^|P|, where  P is the set of parameters. The volume of the parameter space is (2*MAX_FLOAT)**|P|.  The volume of the parameter space that has been completed is the sum of the volumes of true, false, and discarded boxes.  Discarded boxes are all boxes where the width of the box is less than a defined tolerance.  

In many cases, the size of the parameter space is much larger than the effective parameter space.  The effective parameter space may be very small if the parameters are assigned values or tightly bounded.  By default, the effective parameter space is [-MAX_FLOAT, MAX_FLOAT]^|P|, but can be smaller if parameters have defined bounds.

**Comment by jgladwig** [comment]
Restating with some added thoughts/details. I think some added clarity needs to be defined around the stages since there is a processing state as well as progress once processing begins.

Setting the context first...

In general any query is in one of the four states below. For each of the states we want to report some progress data that hints at the how far along the query processing is at the time of the request.

> There is an option to have `coverage` and `progress` where `progress = coverage` when processing but `progress = 0% or 100%` when processing is not started or complete. `coverage` is percent of the possible space that has been searched.

The progress is the bit of interest here so the bulk of the work lives in the updating the progress data but the progress needs to be understandably reported at other processing states.

# Query States
The following are the expected states and some notes on some of what should be returned when a request comes in for the status of a specific query (`/api/queries/<id>`).

- Submitted

    The query is submitted but not yet being processed by a worker.

    > Should contain `parameter_space` field with no results

    > Should contain a `progress` a default field (at `0%`)

- Processing

    The query is currently being processed by a worker.

    > Should contain `parameter_space` field with latest results

    > Should contain a `progress` field with ongoing status and percent of processing completed.

- Errored

    The query encountered an error:
    - submitted data was malformed/incomplete
    - search failed due to some error
    
    > Should contain `error` reason in response.
    
    > Should contain `parameter_space` field with results prior to the error

    > Should contain a `progress` field with the status and percent of processing completed at the time of the error.

- Completed

    The query finished without error.

    > Should contain `parameter_space` field with final results

    > Should contain a `progess` field with the status and the percent should now be at `100%`


# Progress

Once a query is processing it should be able to report some meaningful information back about its current progress.

As things stand the bulk of the work happens within the BoxSearch where we can be:

- Preprocessing data

    This amounts to producing an encoding to submit to the solver.

- Solving

    This amounts to submitting an encoding to the solver and awaiting the results

- Postprocessing data

    This amounts to inspecting the results of a request to the solver and determining how to record the results

**IIRC** these three stages in the box search occur in series any time the search pops a new bit of work of the queue. The work initializes with some initial set of large boxes and then iteratively walks through these three stages. At each postprocessing step it tries to mark the current box as true or false otherwise that box is split and added back to the work queue.

Given the above we appear to have several classes of progress but the last stage seems a good candidate for tracking the whole progress since it is the stage that marks a box as true/false.

> The preprocessing and solving stages will jitter if they try to  include data that has not yet gone through postprocessing since the box beign processing could come back as unknown and need to be divided further.

It seems to me that we can track progress by focusing **only** on the results found during postprocessing. So they would use the sameapproach of tracking how much coverage of the total volume has been marked as true or false (or discarded due to tolerance limits).

> This may have the side effect of a initially slow progress as the initial splitting of the largest boxes can fail to produce any true/false boxes for a while

To incorporate the preprocessing and solving stages into the progress seems to require considering the space of iterative splitting and searching of a box and the boxes within it until the tolerance is hit.
